### ISSUE TITLE
调用AVChatKit.outgoingCall()报空指针异常闪退

### ISSUE THREAD

**Issue by lu553947127** [netease-im/NIM_Android_AVChatKit#3]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference
        at com.netease.nim.avchatkit.common.Handlers.sharedHandler(Handlers.java:37)
        at com.netease.nim.avchatkit.AVChatProfile.activityLaunched(AVChatProfile.java:51)
        at com.netease.nim.avchatkit.activity.AVChatActivity.onCreate(AVChatActivity.java:140)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)

**Comment by 330676687** [comment]
一样

**Comment by lu553947127** [comment]
已经解决了，要初始化一下，就是文档太不详细，坑太多，需要开发者自己去填
